### ISSUE TITLE
optimizeImages should export to dist

### ISSUE THREAD

**Issue by wighawag** [gawlk/svind#113]
Hi, nice template. I am building one myself for a different purpose (planning to publish soon) but it share a similar tech stack and I like what you are doing. thinking to take inpiration for some of it :)

One thing is I am completely new to gulp but noticed that this line : https://github.com/gawlk/svind/blob/513b7e16c4106674d351b54581b4edd8a748164d/gulpfile.js#L105 
should be targeting `dist` and not `public` no ?

I could not test it as in your template, images does not seem to need optimization it output the following in the console :

```
[20:47:08] Starting 'optimizeImages'...
[20:47:10] gulp-imagemin: Minified 0 images
[20:47:10] Finished 'optimizeImages' after 1.9 s
```

**Comment by gawlk** [comment]
Great catch, fixed in the latest commit 👍
